# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setempty.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(674, 465)
        self.btnOK = QtWidgets.QPushButton(Dialog)
        self.btnOK.setGeometry(QtCore.QRect(560, 430, 111, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnOK.setFont(font)
        self.btnOK.setObjectName("btnOK")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 658, 411))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 658, 389))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_3.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_3.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout_3.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout_3.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout_3.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_8.setObjectName("checkBox_8")
        self.verticalLayout_3.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout_3.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout_3.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout_3.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout_3.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_13.setObjectName("checkBox_13")
        self.verticalLayout_3.addWidget(self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_14.setObjectName("checkBox_14")
        self.verticalLayout_3.addWidget(self.checkBox_14)
        self.checkBox_15 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_15.setObjectName("checkBox_15")
        self.verticalLayout_3.addWidget(self.checkBox_15)
        self.checkBox_16 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_16.setObjectName("checkBox_16")
        self.verticalLayout_3.addWidget(self.checkBox_16)
        self.checkBox_17 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_17.setObjectName("checkBox_17")
        self.verticalLayout_3.addWidget(self.checkBox_17)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_18 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_18.setObjectName("checkBox_18")
        self.verticalLayout_2.addWidget(self.checkBox_18)
        self.checkBox_19 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_19.setObjectName("checkBox_19")
        self.verticalLayout_2.addWidget(self.checkBox_19)
        self.checkBox_20 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_20.setObjectName("checkBox_20")
        self.verticalLayout_2.addWidget(self.checkBox_20)
        self.checkBox_21 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_21.setObjectName("checkBox_21")
        self.verticalLayout_2.addWidget(self.checkBox_21)
        self.checkBox_22 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_22.setObjectName("checkBox_22")
        self.verticalLayout_2.addWidget(self.checkBox_22)
        self.checkBox_23 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_23.setObjectName("checkBox_23")
        self.verticalLayout_2.addWidget(self.checkBox_23)
        self.checkBox_24 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_24.setObjectName("checkBox_24")
        self.verticalLayout_2.addWidget(self.checkBox_24)
        self.checkBox_25 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_25.setObjectName("checkBox_25")
        self.verticalLayout_2.addWidget(self.checkBox_25)
        self.checkBox_26 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_26.setObjectName("checkBox_26")
        self.verticalLayout_2.addWidget(self.checkBox_26)
        self.checkBox_27 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_27.setObjectName("checkBox_27")
        self.verticalLayout_2.addWidget(self.checkBox_27)
        self.checkBox_28 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_28.setObjectName("checkBox_28")
        self.verticalLayout_2.addWidget(self.checkBox_28)
        self.checkBox_29 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_29.setObjectName("checkBox_29")
        self.verticalLayout_2.addWidget(self.checkBox_29)
        self.checkBox_30 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_30.setObjectName("checkBox_30")
        self.verticalLayout_2.addWidget(self.checkBox_30)
        self.checkBox_31 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_31.setObjectName("checkBox_31")
        self.verticalLayout_2.addWidget(self.checkBox_31)
        self.checkBox_32 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_32.setObjectName("checkBox_32")
        self.verticalLayout_2.addWidget(self.checkBox_32)
        self.checkBox_33 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_33.setObjectName("checkBox_33")
        self.verticalLayout_2.addWidget(self.checkBox_33)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Пустые поля"))
        self.btnOK.setText(_translate("Dialog", "Принять"))
        self.checkBox.setText(_translate("Dialog", "Название документа"))
        self.checkBox_2.setText(_translate("Dialog", "Организация"))
        self.checkBox_3.setText(_translate("Dialog", "ОГРН"))
        self.checkBox_4.setText(_translate("Dialog", "КПП"))
        self.checkBox_5.setText(_translate("Dialog", "Вид документа"))
        self.checkBox_6.setText(_translate("Dialog", "Статус документа"))
        self.checkBox_7.setText(_translate("Dialog", "Подтверждение утраты"))
        self.checkBox_8.setText(_translate("Dialog", "Подтверждение обмена"))
        self.checkBox_9.setText(_translate("Dialog", "Уровень образования"))
        self.checkBox_10.setText(_translate("Dialog", "Серия документа"))
        self.checkBox_11.setText(_translate("Dialog", "Номер документа"))
        self.checkBox_12.setText(_translate("Dialog", "Дата выдачи"))
        self.checkBox_13.setText(_translate("Dialog", "Регистрационный номер"))
        self.checkBox_14.setText(_translate("Dialog", "Код специальности, направления подготовки"))
        self.checkBox_15.setText(_translate("Dialog", "Наименование специальности, направления подготовки"))
        self.checkBox_16.setText(_translate("Dialog", "Наименование квалификации"))
        self.checkBox_17.setText(_translate("Dialog", "Образовательная программа"))
        self.checkBox_18.setText(_translate("Dialog", "Год поступления"))
        self.checkBox_19.setText(_translate("Dialog", "Год окончания"))
        self.checkBox_20.setText(_translate("Dialog", "Срок обучения, лет"))
        self.checkBox_21.setText(_translate("Dialog", "Фамилия получателя"))
        self.checkBox_22.setText(_translate("Dialog", "Имя получателя"))
        self.checkBox_23.setText(_translate("Dialog", "Отчество получателя"))
        self.checkBox_24.setText(_translate("Dialog", "Дата рождения получателя"))
        self.checkBox_25.setText(_translate("Dialog", "Пол получателя"))
        self.checkBox_26.setText(_translate("Dialog", "Наименование документа об образовании (оригинала)"))
        self.checkBox_27.setText(_translate("Dialog", "Серия (оригинала)"))
        self.checkBox_28.setText(_translate("Dialog", "Серия (оригинала)"))
        self.checkBox_29.setText(_translate("Dialog", "Регистрационный N (оригинала)"))
        self.checkBox_30.setText(_translate("Dialog", "Дата выдачи (оригинала)"))
        self.checkBox_31.setText(_translate("Dialog", "Фамилия получателя (оригинала)"))
        self.checkBox_32.setText(_translate("Dialog", "Имя получателя (оригинала)"))
        self.checkBox_33.setText(_translate("Dialog", "Отчество получателя (оригинала)"))
